// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJM32i72R2hewOAp2-HNZY63EkH9GoWVU',
    appId: '1:258200808152:web:5a2118857223a4e75545ad',
    messagingSenderId: '258200808152',
    projectId: 'sanayi-omer-tr',
    authDomain: 'sanayi-omer-tr.firebaseapp.com',
    storageBucket: 'sanayi-omer-tr.firebasestorage.app',
    measurementId: 'G-SS43B50P30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8LRMF0poH-5Gt5Bp2os95B4Ld2wiflf4',
    appId: '1:258200808152:android:4df336be2a308f465545ad',
    messagingSenderId: '258200808152',
    projectId: 'sanayi-omer-tr',
    storageBucket: 'sanayi-omer-tr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkL8HeqlK7BL3FmolpcEFdqhF_-qXDcDQ',
    appId: '1:258200808152:ios:59c75a25e32aa1495545ad',
    messagingSenderId: '258200808152',
    projectId: 'sanayi-omer-tr',
    storageBucket: 'sanayi-omer-tr.firebasestorage.app',
    iosBundleId: 'com.example.sanayiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkL8HeqlK7BL3FmolpcEFdqhF_-qXDcDQ',
    appId: '1:258200808152:ios:59c75a25e32aa1495545ad',
    messagingSenderId: '258200808152',
    projectId: 'sanayi-omer-tr',
    storageBucket: 'sanayi-omer-tr.firebasestorage.app',
    iosBundleId: 'com.example.sanayiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJM32i72R2hewOAp2-HNZY63EkH9GoWVU',
    appId: '1:258200808152:web:db0c8b7b1a9e1baf5545ad',
    messagingSenderId: '258200808152',
    projectId: 'sanayi-omer-tr',
    authDomain: 'sanayi-omer-tr.firebaseapp.com',
    storageBucket: 'sanayi-omer-tr.firebasestorage.app',
    measurementId: 'G-DF1FEFQYQM',
  );
}
